language: python
python:
  - 2.7
services:
  - docker

before_install:
  - pip install flake8
  - docker-compose build

script:
  # Style linting for the application itself
  - flake8 primes.py

  # Does the container run, start the Python primes script
  # and offer some usage instructions?
  - docker-compose run --rm primes | grep help

  # Can the app understand we want to generate five numbers?
  - docker-compose run --rm primes -p 5 | wc -l | grep 5

  # Can we guarantee these are primes?
  # We know the 20,000'th prime is 224737, from external sources.
  # e.g. https://www.dcode.fr/prime-numbers-search 
  - docker-compose run --rm primes -p 20000| grep "Prime 20000" | grep 224737
